// <auto-generated />
using System;
using Biblioteka.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteka.Web.Migrations
{
    [DbContext(typeof(BibliotekaDbContext))]
    [Migration("20260313104520_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Biblioteka.Web.Data.Entities.HistoriaHasla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNadania")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_nadania");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("haslo_hash");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uzytkownik_id");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Historia_Hasel");
                });

            modelBuilder.Entity("Biblioteka.Web.Data.Entities.Uprawnienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uprawnienia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Administrator",
                            Opis = "Pełny dostęp do systemu"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Bibliotekarz",
                            Opis = "Zarządzanie książkami i wypożyczeniami"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Klient",
                            Opis = "Podstawowy dostęp dla czytelników"
                        });
                });

            modelBuilder.Entity("Biblioteka.Web.Data.Entities.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BlokadaDo")
                        .HasColumnType("TEXT")
                        .HasColumnName("blokada_do");

                    b.Property<bool>("CzyZablokowany")
                        .HasColumnType("INTEGER")
                        .HasColumnName("czy_zablokowany");

                    b.Property<bool>("CzyZapomniany")
                        .HasColumnType("INTEGER")
                        .HasColumnName("czy_zapomniany");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_urodzenia");

                    b.Property<DateTime?>("DataZapomnienia")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_zapomnienia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasloHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("haslo_hash");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kod_pocztowy");

                    b.Property<int>("LiczbaBlednychLogowan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("liczba_blednych_logowan");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerLokalu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerPosesji")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("numer_posesji");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZapomnianyPrzezId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("zapomniany_przez_id");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CzyZablokowany = false,
                            CzyZapomniany = false,
                            DataUrodzenia = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@biblioteka.pl",
                            HasloHash = "admin123",
                            Imie = "Emil",
                            KodPocztowy = "90-001",
                            LiczbaBlednychLogowan = 0,
                            Login = "admin",
                            Miejscowosc = "Łódź",
                            Nazwisko = "Górski",
                            NumerLokalu = "",
                            NumerPosesji = "1",
                            Pesel = "90010112345",
                            Plec = "mężczyzna",
                            Telefon = "123456789",
                            Ulica = "Piotrkowska"
                        });
                });

            modelBuilder.Entity("Uzytkownik_Uprawnienia", b =>
                {
                    b.Property<int>("uprawnienie_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("uzytkownik_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("uprawnienie_id", "uzytkownik_id");

                    b.HasIndex("uzytkownik_id");

                    b.ToTable("Uzytkownik_Uprawnienia");
                });

            modelBuilder.Entity("Biblioteka.Web.Data.Entities.HistoriaHasla", b =>
                {
                    b.HasOne("Biblioteka.Web.Data.Entities.Uzytkownik", "Uzytkownik")
                        .WithMany("HistoriaHasel")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Uzytkownik_Uprawnienia", b =>
                {
                    b.HasOne("Biblioteka.Web.Data.Entities.Uprawnienie", null)
                        .WithMany()
                        .HasForeignKey("uprawnienie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteka.Web.Data.Entities.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("uzytkownik_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biblioteka.Web.Data.Entities.Uzytkownik", b =>
                {
                    b.Navigation("HistoriaHasel");
                });
#pragma warning restore 612, 618
        }
    }
}
