// <auto-generated />
using System;
using Biblioteka.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteka.Web.Migrations
{
    [DbContext(typeof(BibliotekaDbContext))]
    [Migration("20260312215124_MakePasswordNullable")]
    partial class MakePasswordNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Biblioteka.Web.Data.Entities.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BlokadaDo")
                        .HasColumnType("TEXT")
                        .HasColumnName("blokada_do");

                    b.Property<bool>("CzyZablokowany")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyZapomniany")
                        .HasColumnType("INTEGER")
                        .HasColumnName("czy_zapomniany");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_urodzenia");

                    b.Property<DateTime?>("DataZapomnienia")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_zapomnienia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("haslo_hash");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kod_pocztowy");

                    b.Property<int>("LiczbaBlednychLogowan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("liczba_blednych_logowan");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerLokalu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerPosesji")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("numer_posesji");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZapomnianyPrzezId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("zapomniany_przez_id");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
